version: 2

models:
  - name: fct_trips
    description: fact data for all the trips
    columns:
      - name: trip_id
        description: Primary key for trips
        tests:
          - unique
          - not_null
      
      - name: vendorid
        tests:
          - not_null
      
      - name: payment_type
        description: Payment method code
        tests:
          - accepted_values:
              values:
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
      
      - name: pickup_locationid
        description: Taxi zone where trip started
        tests:
          - relationships:
              to: ref('taxi_zone_lookup')
              field: locationid